### ISSUE TITLE
cmsis_device_f1/Include/stm32f103xb.h line L4223-L4232 lose "TIM_CCER_CC4NP" define

### ISSUE THREAD

**Issue by kex2017** [STMicroelectronics/cmsis_device_f1#1]
**Caution**
The Issues are strictly limited for the reporting of problem encountered with the software provided in this project.
For any other problem related to the STM32 product, the performance, the hardware characteristics and boards, the tools the environment in general, please post a topic in the [ST Community/STM32 MCUs forum](https://community.st.com/s/group/0F90X000000AXsASAW/stm32-mcus).

**Describe the set-up**
 * The board (either ST RPN reference or your custom board)
 * IDE or at least the compiler and its version

**Describe the bug**

**How To Reproduce**
1. Indicate the global behavior of your application project

2. The modules that you suspect to be the cause of the problem (Driver, BSP, MW ...)

3. The use case that generates the problem

4. How we can reproduce the problem

**Additional context**
If you have a first analysis or patch correction, thank you to share your proposal.

**Screenshots**

**Comment by ASELSTM** [comment]
Hi @kex2017,

**TIM_CCER_CC4NP** is not defined for STM32F103xx devices and it is not defined for any of the stm32F1XX devices. Actually, this bit definition was deleted from the STM32F1 cmsis device files since release **v4.2.0**.

You may also refer to the TIMx_CCER register mapping described in the  **"capture/compare enable register (TIMx_CCER)"** sections of the [ STM32F103xx reference manual](https://www.st.com/resource/en/reference_manual/cd00171190-stm32f101xx-stm32f102xx-stm32f103xx-stm32f105xx-and-stm32f107xx-advanced-arm-based-32-bit-mcus-stmicroelectronics.pdf).

Please allow me then to close this thread. Thank you for your comprehension and thank you again for your contribution.

With regards,
